name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "lambda function/requirements.txt" -t ./package
          cp -r "lambda function/"* ./package/

      - name: Package Lambda function
        run: |
          cd ./package
          zip -r ../lambda_function.zip . -x "*.git*" "*.github*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name emailExtractor2 \
            --zip-file fileb://lambda_function.zip
